# Generated by Django 5.2.7 on 2025-12-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='status',
        ),
    ]
