# Generated by Django 5.2.7 on 2026-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='package_type',
            field=models.CharField(choices=[('annual_health_packages', 'Annual Health Packages'), ('special_packages', 'Special Packages'), ('regular_packages', 'Regular Packages')], default='regular_packages', max_length=50),
        ),
    ]
