# Generated by Django 5.2.7 on 2026-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0002_healthpackage_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackage',
            name='package_type',
            field=models.CharField(choices=[('annual_health_package', 'Annual Health Packages'), ('special_package', 'Special Packages'), ('regular_package', 'Regular Packages')], default='regular_package', max_length=50),
        ),
    ]
