# Generated by Django 5.2.7 on 2026-01-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_service', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymcenter',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
        migrations.AlterField(
            model_name='gymcenter',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.state'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.state'),
        ),
    ]
