# Generated by Django 5.2.7 on 2026-01-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='relationship',
        ),
    ]
