# Generated by Django 4.2.7 on 2025-12-17 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnostic_center", "0002_alter_diagnosticcenter_options_and_more"),
        ("corporates", "0001_initial"),
        ("cases", "0001_initial"),
        ("dependants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "consultation_filter",
            "0002_alter_vendor_options_vendor_business_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="corporate",
            field=models.ForeignKey(
                blank=True,
                help_text="Corporate client if this is an employee booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="corporates.corporate",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="dependant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="dependants.dependant",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="diagnostic_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="diagnostic_center.diagnosticcenter",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="user",
            field=models.ForeignKey(
                help_text="Customer/Patient who created this case",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor handling this case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="consultation_filter.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["case_id"], name="cases_case_id_ac4163_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["status"], name="cases_status_e2ca9e_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["service_type"], name="cases_service_78075d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["vendor"], name="cases_vendor__914181_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["assigned_to"], name="cases_assigne_b4713e_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["scheduled_date"], name="cases_schedul_0cfcab_idx"
            ),
        ),
    ]
