# Generated by Django 4.2.7 on 2025-12-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="advance_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="case",
            name="agent_employee_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="agent_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="agent_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="application_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="bank_branch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="case_received_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("corporate_employee", "Corporate Employee"),
                    ("dependant", "Dependant"),
                    ("hni", "HNI/VIP"),
                ],
                default="individual",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="employee_to_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount employee pays (rest covered by corporate)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="followup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="followup_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="generic_tests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="home_visit_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="case",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="medical_tests",
            field=models.TextField(
                blank=True, help_text="Comma-separated test names", null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("prepaid", "Prepaid"),
                    ("postpaid", "Postpaid"),
                    ("corporate", "Corporate Billing"),
                    ("insurance", "Insurance"),
                    ("cod", "Cash on Delivery"),
                ],
                default="prepaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="received_by_department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="received_by_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="received_by_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="received_by_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="service_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="case",
            name="utr_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="visit_type",
            field=models.CharField(
                choices=[
                    ("home", "Home Visit"),
                    ("center", "At Center"),
                    ("video", "Video Consultation"),
                    ("hybrid", "Hybrid"),
                ],
                default="center",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="source",
            field=models.CharField(
                choices=[
                    ("app", "Mobile App"),
                    ("web", "Website"),
                    ("crm", "CRM Manual Entry"),
                    ("api", "External API"),
                    ("call", "Call Center"),
                    ("email", "Email"),
                    ("walkin", "Walk-in"),
                    ("hr_portal", "HR Portal"),
                ],
                default="web",
                max_length=20,
            ),
        ),
    ]
