# Generated by Django 4.2.7 on 2025-12-27 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor_details", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0003_case_account_holder_name_case_account_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasePrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("prescription_number", models.CharField(max_length=50, unique=True)),
                ("prescribed_by_name", models.CharField(max_length=255)),
                ("prescribed_at", models.DateTimeField(auto_now_add=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("advice", models.TextField(blank=True, null=True)),
                (
                    "prescription_file",
                    models.FileField(blank=True, null=True, upload_to="prescriptions/"),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "db_table": "case_prescriptions",
                "ordering": ["-prescribed_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("e_consultation", "E-Consultation"),
                            ("specialist", "Specialist Consultation"),
                            ("face_to_face", "Face to Face"),
                            ("video", "Video Consultation"),
                            ("chat", "Chat Consultation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "consultation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("doctor_assigned", "Doctor Assigned"),
                            ("scheduled", "Scheduled"),
                            ("waiting", "Waiting for Patient"),
                            ("in_progress", "In Progress"),
                            ("prescription_pending", "Prescription Pending"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("appointment_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_duration",
                    models.PositiveIntegerField(
                        default=15, help_text="Duration in minutes"
                    ),
                ),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("meeting_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "meeting_password",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("chief_complaint", models.TextField(blank=True, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                (
                    "symptom_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("medical_history", models.TextField(blank=True, null=True)),
                ("current_medications", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("treatment_plan", models.TextField(blank=True, null=True)),
                ("doctor_notes", models.TextField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True, null=True)),
                (
                    "consultation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_ended_at", models.DateTimeField(blank=True, null=True)),
                ("actual_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("recording_available", models.BooleanField(default=False)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_details",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_cases",
                        to="doctor_details.doctorprofessionaldetails",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "consultation_cases",
                "ordering": ["-appointment_datetime"],
            },
        ),
        migrations.CreateModel(
            name="QCChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("documentation", "Documentation"),
                            ("process", "Process Compliance"),
                            ("communication", "Communication"),
                            ("technical", "Technical"),
                            ("customer_service", "Customer Service"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "weightage",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("is_critical", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "applicable_service_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of service types this checklist applies to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qc_checklists",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeleMERQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("pulse_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "medical_history_responses",
                    models.JSONField(blank=True, default=dict),
                ),
                ("is_smoker", models.BooleanField(blank=True, null=True)),
                (
                    "smoking_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_alcohol_consumer", models.BooleanField(blank=True, null=True)),
                (
                    "alcohol_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "exercise_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("family_history", models.JSONField(blank=True, default=dict)),
                ("current_medications", models.TextField(blank=True, null=True)),
                ("known_allergies", models.TextField(blank=True, null=True)),
                ("chronic_conditions", models.TextField(blank=True, null=True)),
                ("general_appearance", models.TextField(blank=True, null=True)),
                ("examination_findings", models.TextField(blank=True, null=True)),
                ("doctor_remarks", models.TextField(blank=True, null=True)),
                ("verified_by_doctor", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audio_recording",
                    models.FileField(
                        blank=True, null=True, upload_to="tele_mer_recordings/"
                    ),
                ),
                (
                    "video_recording",
                    models.FileField(
                        blank=True, null=True, upload_to="tele_mer_recordings/"
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tele_mer",
                        to="cases.case",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tele_mer",
                        to="cases.consultationcase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verifying_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_tele_mers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tele_mer_questionnaires",
            },
        ),
        migrations.CreateModel(
            name="QCReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("qc_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("rework", "Sent for Rework"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "documentation_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "process_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "communication_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("critical_issues", models.TextField(blank=True, null=True)),
                ("rework_required", models.BooleanField(default=False)),
                ("rework_reason", models.TextField(blank=True, null=True)),
                ("rework_deadline", models.DateTimeField(blank=True, null=True)),
                ("rework_completed", models.BooleanField(default=False)),
                ("rework_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_reviews",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_reviews_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_qc_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("medicine_name", models.CharField(max_length=255)),
                (
                    "generic_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("timing", models.CharField(blank=True, max_length=100, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="cases.caseprescription",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prescription_medicines",
            },
        ),
        migrations.CreateModel(
            name="HealthCheckupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Health Checkup"),
                            ("pre_employment", "Pre-Employment"),
                            ("periodic", "Periodic Checkup"),
                            ("special", "Special Checkup"),
                            ("executive", "Executive Health Checkup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("report_pending", "Report Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("package_id", models.PositiveIntegerField(blank=True, null=True)),
                ("tests_included", models.JSONField(blank=True, default=list)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.TimeField(blank=True, null=True)),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("actual_time", models.TimeField(blank=True, null=True)),
                (
                    "center_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("center_address", models.TextField(blank=True, null=True)),
                ("is_home_collection", models.BooleanField(default=False)),
                ("hr_approval_required", models.BooleanField(default=False)),
                ("hr_approved", models.BooleanField(default=False)),
                (
                    "hr_approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hr_approved_at", models.DateTimeField(blank=True, null=True)),
                ("report_generated", models.BooleanField(default=False)),
                ("report_generated_at", models.DateTimeField(blank=True, null=True)),
                ("report_shared_with_employee", models.BooleanField(default=False)),
                ("report_shared_with_hr", models.BooleanField(default=False)),
                (
                    "overall_health_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("critical_findings", models.TextField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True, null=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checkup",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_checkup_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("open", "Open Cases"),
                            ("assigned", "Assigned Cases"),
                            ("pending_vendor", "Pending Vendor"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("escalated", "Escalated"),
                            ("qc_pending", "QC Pending"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "filter_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON filter criteria for this queue",
                    ),
                ),
                (
                    "assigned_team",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sla_hours", models.PositiveIntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_queues",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="caseprescription",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="cases.consultationcase",
            ),
        ),
        migrations.AddField(
            model_name="caseprescription",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseprescription",
            name="prescribed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseprescription",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CaseEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_number", models.CharField(max_length=50, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("level_1", "Level 1 - Team Lead"),
                            ("level_2", "Level 2 - Manager"),
                            ("level_3", "Level 3 - Senior Manager"),
                            ("level_4", "Level 4 - Director"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sla_breach", "SLA Breach"),
                            ("customer_complaint", "Customer Complaint"),
                            ("vendor_issue", "Vendor Issue"),
                            ("quality_issue", "Quality Issue"),
                            ("payment_issue", "Payment Issue"),
                            ("technical_issue", "Technical Issue"),
                            ("urgent_request", "Urgent Request"),
                            ("vip_customer", "VIP Customer"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("escalated_at", models.DateTimeField(auto_now_add=True)),
                ("resolution", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("target_resolution_time", models.DateTimeField(blank=True, null=True)),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_escalations",
                "ordering": ["-escalated_at"],
            },
        ),
        migrations.CreateModel(
            name="QCChecklistResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("na", "Not Applicable"),
                            ("partial", "Partial"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="cases.qcchecklist",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_responses",
                        to="cases.qcreview",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qc_checklist_responses",
                "unique_together": {("qc_review", "checklist_item")},
            },
        ),
    ]
