# Generated by Django 4.2.7 on 2025-12-17 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("location", "0001_initial"),
        ("consultation_filter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["-priority", "name"]},
        ),
        migrations.AddField(
            model_name="vendor",
            name="business_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="cities_served",
            field=models.ManyToManyField(
                blank=True, related_name="vendors", to="location.city"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique vendor code e.g., APOLLO, HEALTHIANS",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="e_consultation",
            field=models.BooleanField(
                default=False, help_text="Supports e-consultation"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="home_collection",
            field=models.BooleanField(
                default=False, help_text="Supports home sample collection"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="in_clinic",
            field=models.BooleanField(
                default=False, help_text="Supports in-clinic visits"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_pan_india",
            field=models.BooleanField(default=False, help_text="Serves all cities"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="priority",
            field=models.IntegerField(
                default=0, help_text="Higher priority vendors shown first"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("diagnostic", "Diagnostic Lab"),
                    ("pharmacy", "Pharmacy"),
                    ("consultation", "Consultation"),
                    ("gym", "Gym/Fitness"),
                    ("eyedental", "Eye & Dental"),
                    ("multi", "Multi-Service"),
                ],
                default="diagnostic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VendorAPIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("api_base_url", models.URLField(help_text="Base URL for vendor API")),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "auth_token",
                    models.TextField(
                        blank=True, help_text="OAuth token if applicable", null=True
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional vendor-specific configuration",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL for vendor callbacks",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_config",
                        to="consultation_filter.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_api_configs",
            },
        ),
        migrations.CreateModel(
            name="VendorServiceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("test", "Lab Test"),
                            ("package", "Health Package"),
                            ("consultation", "Doctor Consultation"),
                            ("pharmacy", "Pharmacy Order"),
                            ("home_visit", "Home Visit Charges"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "internal_service_id",
                    models.CharField(
                        help_text="Internal test/package/doctor ID", max_length=100
                    ),
                ),
                (
                    "vendor_service_id",
                    models.CharField(help_text="Vendor's service ID", max_length=100),
                ),
                ("vendor_service_name", models.CharField(max_length=255)),
                ("vendor_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("our_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_mappings",
                        to="consultation_filter.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_service_mappings",
                "unique_together": {("vendor", "service_type", "internal_service_id")},
            },
        ),
    ]
