# Generated by Django 4.2.7 on 2025-12-29 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("location", "0001_initial"),
        ("eyedental_care", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dentaltreatment",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dentalvendoraddress",
            options={"ordering": ["vendor__name"]},
        ),
        migrations.AlterModelOptions(
            name="eyedentalvoucher",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="eyetreatment",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="eyevendoraddress",
            options={"ordering": ["vendor__name"]},
        ),
        migrations.AddField(
            model_name="dentaltreatment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dental_vendors",
                to="location.city",
            ),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Center name (if different from vendor)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dental_vendors",
                to="location.state",
            ),
        ),
        migrations.AddField(
            model_name="dentalvendoraddress",
            name="treatments",
            field=models.ManyToManyField(
                blank=True, related_name="vendors", to="eyedental_care.dentaltreatment"
            ),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="appointment_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="eyetreatment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eye_vendors",
                to="location.city",
            ),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Center name (if different from vendor)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eye_vendors",
                to="location.state",
            ),
        ),
        migrations.AddField(
            model_name="eyevendoraddress",
            name="treatments",
            field=models.ManyToManyField(
                blank=True, related_name="vendors", to="eyedental_care.eyetreatment"
            ),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="contact_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="state",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eye_dental_vouchers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="dentaltreatment",
            table="dental_treatments",
        ),
        migrations.AlterModelTable(
            name="dentalvendoraddress",
            table="dental_vendor_addresses",
        ),
        migrations.AlterModelTable(
            name="eyedentalvoucher",
            table="eye_dental_vouchers",
        ),
        migrations.AlterModelTable(
            name="eyetreatment",
            table="eye_treatments",
        ),
        migrations.AlterModelTable(
            name="eyevendoraddress",
            table="eye_vendor_addresses",
        ),
    ]
