# Generated by Django 5.2.7 on 2026-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyedental_care', '0002_remove_eyedentalvoucher_dental_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyedentalcarebooking',
            name='booking_type',
            field=models.CharField(choices=[('treatment', 'Treatment'), ('book_appointment', 'Book Appointment')], default='null', max_length=20),
            preserve_default=False,
        ),
    ]
