# Generated by Django 4.2.7 on 2025-12-29 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eyedental_care", "0002_alter_dentaltreatment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EyeDentalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("eye", "Eye Care"), ("dental", "Dental Care")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("detailed_description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="eyedental_services/"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "eye_dental_services",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="comment",
            field=models.TextField(
                blank=True, default="", help_text="Admin remarks/notes"
            ),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="corporate_branch_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="corporate_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="dependant_id",
            field=models.IntegerField(
                blank=True, help_text="EmployeeDependentDetailsId", null=True
            ),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="service_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="treatment_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last updated by admin user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_eye_dental_vouchers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="vendor_address_snapshot",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="eyedentalvoucher",
            name="vendor_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="dental_treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="eyedental_care.dentaltreatment",
            ),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="dental_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="eyedental_care.dentalvendoraddress",
            ),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="eye_treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="eyedental_care.eyetreatment",
            ),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="eye_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="eyedental_care.eyevendoraddress",
            ),
        ),
        migrations.AlterField(
            model_name="eyedentalvoucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("fresh", "Fresh Case"),
                    ("pending", "Pending"),
                    ("in_process", "In Process"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("completed", "Completed"),
                ],
                default="fresh",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EyeDentalVoucherRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="eyedental_care.eyedentalvoucher",
                    ),
                ),
            ],
            options={
                "db_table": "eye_dental_voucher_remarks",
                "ordering": ["-created_at"],
            },
        ),
    ]
