# Generated by Django 4.2.7 on 2025-12-26 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("provider_name", models.CharField(max_length=50)),
                ("event_type", models.CharField(max_length=100)),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                ("headers", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processing_result", models.TextField(blank=True)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider_name", "event_type"],
                        name="providers_p_provide_85ee94_idx",
                    ),
                    models.Index(
                        fields=["reference_id"], name="providers_p_referen_a174f6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Provider identifier e.g., 'apollo', 'onemg'",
                        max_length=50,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("diagnostics", "Diagnostics"),
                            ("pharmacy", "Pharmacy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_base_url", models.URLField(blank=True)),
                (
                    "api_credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Encrypted credentials like api_key, username, password",
                    ),
                ),
                (
                    "additional_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration like agreement_id, client_id",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("supports_tele_consultation", models.BooleanField(default=False)),
                ("supports_video_consultation", models.BooleanField(default=False)),
                ("supports_in_clinic", models.BooleanField(default=False)),
                ("supports_home_collection", models.BooleanField(default=False)),
                ("supports_walk_in", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider_type", "name"],
                "unique_together": {("name", "provider_type")},
            },
        ),
        migrations.CreateModel(
            name="ExternalLabBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("provider_name", models.CharField(max_length=50)),
                ("provider_booking_id", models.CharField(max_length=100)),
                ("provider_order_id", models.CharField(blank=True, max_length=100)),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_mobile", models.CharField(max_length=15)),
                ("patient_email", models.EmailField(blank=True, max_length=254)),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("home_collection", "Home Collection"),
                            ("walk_in", "Walk-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("center_id", models.CharField(blank=True, max_length=100)),
                ("center_name", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("booking_date", models.DateField()),
                ("slot_time", models.TimeField(blank=True, null=True)),
                ("tests", models.JSONField(default=list)),
                ("packages", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("sample_collected", "Sample Collected"),
                            ("in_progress", "In Progress"),
                            ("report_ready", "Report Ready"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(auto_now=True)),
                ("phlebotomist_name", models.CharField(blank=True, max_length=200)),
                ("phlebotomist_phone", models.CharField(blank=True, max_length=15)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reports_available", models.BooleanField(default=False)),
                ("report_urls", models.JSONField(default=list)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_lab_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider_name", "provider_booking_id"],
                        name="providers_e_provide_aff054_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="providers_e_user_id_984b00_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("provider_name", models.CharField(max_length=50)),
                ("provider_appointment_id", models.CharField(max_length=100)),
                ("provider_booking_id", models.CharField(blank=True, max_length=100)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("diagnostic", "Diagnostic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("doctor_id", models.CharField(blank=True, max_length=100)),
                ("doctor_name", models.CharField(blank=True, max_length=200)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                ("hospital_id", models.CharField(blank=True, max_length=100)),
                ("hospital_name", models.CharField(blank=True, max_length=200)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("consultation_type", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("meeting_link", models.URLField(blank=True)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_reference",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment_date", "-appointment_time"],
                "indexes": [
                    models.Index(
                        fields=["provider_name", "provider_appointment_id"],
                        name="providers_e_provide_e27a9b_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="providers_e_user_id_0d76a1_idx"
                    ),
                    models.Index(
                        fields=["appointment_date"],
                        name="providers_e_appoint_21b890_idx",
                    ),
                ],
            },
        ),
    ]
