# Generated by Django 5.2.7 on 2025-12-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_filter', '0001_initial'),
        ('doctor_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofessionaldetails',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='doctorprofessionaldetails',
            name='language',
        ),
        migrations.RemoveField(
            model_name='doctorprofessionaldetails',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctorprofessionaldetails',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='consultation_filter.language'),
        ),
        migrations.AddField(
            model_name='doctorprofessionaldetails',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='consultation_filter.doctorspeciality'),
        ),
    ]
