# Generated by Django 5.2.7 on 2026-01-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0002_doctorprofessionaldetails_qualification_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpersonaldetails',
            name='city',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='location.city'),
            preserve_default=False,
        ),
    ]
