# Generated by Django 5.2.7 on 2025-12-15 09:18

import apps.appointments.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('consultation_filter', '0001_initial'),
        ('dependants', '0001_initial'),
        ('diagnostic_center', '0001_initial'),
        ('doctor_details', '0001_initial'),
        ('eyedental_care', '0001_initial'),
        ('health_packages', '0001_initial'),
        ('labfilter', '0001_initial'),
        ('labtest', '0001_initial'),
        ('sponsored_packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appointment_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('for_whom', models.CharField(choices=[('self', 'Self'), ('dependant', 'Dependant')], default='self', max_length=20)),
                ('item_type', models.CharField(choices=[('test', 'Test'), ('health_package', 'Health Package'), ('sponsored_package', 'Sponsored Package'), ('appointment', 'Lab Appointment'), ('doctor_appointment', 'Doctor Appointment'), ('dental_appointment', 'Dental Appointment'), ('eye_appointment', 'Eye Appointment')], default='test', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mode', models.CharField(blank=True, choices=[('video', 'Video Consultation'), ('tele', 'Telephonic Consultation'), ('in-person', 'In-Person Consultation')], max_length=10, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_last4', models.CharField(blank=True, max_length=10, null=True)),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dental_vendor_centers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eyedental_care.dentalvendoraddress')),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_created_main', to='dependants.dependant')),
                ('diagnostic_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic_center.diagnosticcenter')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_details.doctorprofessionaldetails')),
                ('eye_vendor_centers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eyedental_care.eyevendoraddress')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_main', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_filter.vendor')),
                ('visit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labfilter.visittype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_details.doctorprofessionaldetails')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labtest.test')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='medical_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('test', 'Test'), ('health_package', 'Health Package'), ('sponsored_package', 'Sponsored Package'), ('appointment', 'Lab Appointment'), ('doctor_appointment', 'Doctor Appointment'), ('dental_appointment', 'Dental Appointment'), ('eye_appointment', 'Eye Appointment')], default='test', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.CharField(max_length=20, blank=True, default=apps.appointments.models.CartItem.generate_appointment_code, editable=False, null=True, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=150)),
                ('symptoms', models.TextField(blank=True, max_length=1000)),
                ('mode', models.CharField(blank=True, choices=[('video', 'Video Consultation'), ('tele', 'Telephonic Consultation'), ('in-person', 'In-Person Consultation')], max_length=10, null=True)),
                ('for_whom', models.CharField(choices=[('self', 'Self'), ('dependant', 'Dependant')], default='self', max_length=20)),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TimeField(null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('selected_date', models.DateField(blank=True, null=True)),
                ('selected_time', models.TimeField(blank=True, null=True)),
                ('slot_confirmed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appointments.cart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dental_vendor_centers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eyedental_care.dentalvendoraddress')),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dependants.dependant')),
                ('diagnostic_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic_center.diagnosticcenter')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_details.doctorprofessionaldetails')),
                ('eye_vendor_centers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eyedental_care.eyevendoraddress')),
                ('health_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_packages.healthpackage')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eyedentalcare_specialization', to='consultation_filter.doctorspeciality')),
                ('sponsored_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsored_packages.sponsoredpackage')),
                ('tests', models.ManyToManyField(blank=True, to='labtest.test')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_filter.vendor')),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labfilter.visittype')),
                ('documents', models.ManyToManyField(blank=True, related_name='appointments', to='appointments.reportdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('mode', models.CharField(choices=[('tele', 'Tele Consultation'), ('video', 'Video Consultation')], max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('break_start', models.TimeField(default=datetime.time(13, 0))),
                ('break_end', models.TimeField(default=datetime.time(14, 0))),
                ('slot_duration', models.IntegerField(default=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctor_details.doctorprofessionaldetails')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'mode', 'date', 'start_time', 'end_time'), name='unique_doctor_mode_date_time')],
            },
        ),
    ]
