# Generated by Django 5.2.7 on 2026-01-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dental_vendor_centers',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='eye_vendor_centers',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='dental_vendor_centers',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='eye_vendor_centers',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='vendor',
        ),
    ]
