# Generated by Django 4.2.7 on 2025-12-17 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labtest", "0001_initial"),
        (
            "consultation_filter",
            "0002_alter_vendor_options_vendor_business_address_and_more",
        ),
        ("diagnostic_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosticcenter",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="alternate_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="grade",
            field=models.CharField(
                choices=[
                    ("A", "Grade A - Premium"),
                    ("B", "Grade B - Standard"),
                    ("C", "Grade C - Basic"),
                ],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="has_parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="home_collection",
            field=models.BooleanField(
                default=False, help_text="Supports home sample collection"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="home_collection_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="is_cap_accredited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="is_nabl_accredited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="sunday_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor this DC belongs to (Apollo, Healthians, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostic_centers",
                to="consultation_filter.vendor",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="vendor_dc_id",
            field=models.CharField(
                blank=True,
                help_text="DC ID in vendor's system for API calls",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="diagnosticcenter",
            table="diagnostic_centers",
        ),
        migrations.CreateModel(
            name="DiagnosticCenterTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "turnaround_hours",
                    models.IntegerField(default=24, help_text="Report TAT in hours"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dc_tests",
                        to="diagnostic_center.diagnosticcenter",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dc_tests",
                        to="labtest.test",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "diagnostic_center_tests",
                "unique_together": {("diagnostic_center", "test")},
            },
        ),
    ]
