# Generated by Django 4.2.7 on 2025-12-18 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diagnostic_center", "0002_alter_diagnosticcenter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="accreditation_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="acls_ambulance_count",
            field=models.IntegerField(
                default=0, help_text="Advanced Cardiac Life Support"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="bank_account_holder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="bank_branch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="bank_ifsc_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="bls_ambulance_count",
            field=models.IntegerField(default=0, help_text="Basic Life Support"),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="categorization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="center_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("pending", "Pending Approval"),
                    ("suspended", "Suspended"),
                    ("blacklisted", "Blacklisted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="client_assign",
            field=models.TextField(
                blank=True, help_text="Assigned corporate clients", null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="corporate_group",
            field=models.CharField(
                blank=True, help_text="Parent group name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="corporate_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deactivated_dcs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="deactivation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="deactivation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="delivery_tat",
            field=models.CharField(
                blank=True,
                help_text="Delivery turnaround time",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="doctor_consultants",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="fax_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="google_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="gst_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="has_ambulance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="health_checkup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="home_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="is_iso_certified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="iso_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="landline_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="location_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="dc_logos/"),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="mou_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="mou_signed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("government", "Government"),
                    ("trust", "Trust"),
                    ("corporate", "Corporate Chain"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="partnership_type",
            field=models.CharField(
                choices=[
                    ("empaneled", "Empaneled"),
                    ("partner", "Partner"),
                    ("franchise", "Franchise"),
                    ("owned", "Owned"),
                ],
                default="empaneled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="payment_terms",
            field=models.IntegerField(default=30, help_text="Payment terms in days"),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="priority",
            field=models.IntegerField(default=0, help_text="Higher = shown first"),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("lab", "Standalone Lab"),
                    ("collection_center", "Collection Center"),
                    ("imaging_center", "Imaging Center"),
                ],
                default="lab",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="recognized_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="service_area",
            field=models.TextField(blank=True, help_text="Areas served", null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="service_pincodes",
            field=models.TextField(
                blank=True, help_text="Comma-separated pincodes served", null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="short_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="specialties_available",
            field=models.TextField(
                blank=True, help_text="Comma-separated specialties", null=True
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="specialty_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("multi_specialty", "Multi-Specialty"),
                    ("single_specialty", "Single Specialty"),
                    ("super_specialty", "Super Specialty"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="staff_strength",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="std_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="token_id",
            field=models.CharField(
                blank=True,
                help_text="Vendor registration token",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="unique_name",
            field=models.CharField(
                blank=True,
                help_text="Short unique identifier",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="visit_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="visiting_consultants",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosticcenter",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="DCLaboratoryCapabilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("hematology", models.BooleanField(default=False)),
                ("biochemistry", models.BooleanField(default=False)),
                ("microbiology", models.BooleanField(default=False)),
                ("pathology", models.BooleanField(default=False)),
                ("serology", models.BooleanField(default=False)),
                ("histopathology", models.BooleanField(default=False)),
                ("endocrinology", models.BooleanField(default=False)),
                ("cytology", models.BooleanField(default=False)),
                ("immunology", models.BooleanField(default=False)),
                ("x_ray", models.BooleanField(default=False)),
                ("digital_x_ray", models.BooleanField(default=False)),
                ("ultra_sound", models.BooleanField(default=False)),
                ("color_doppler", models.BooleanField(default=False)),
                ("mammogram", models.BooleanField(default=False)),
                ("ct_scan", models.BooleanField(default=False)),
                ("mri", models.BooleanField(default=False)),
                ("pet_scan", models.BooleanField(default=False)),
                ("nuclear_imaging", models.BooleanField(default=False)),
                ("ecg", models.BooleanField(default=False)),
                (
                    "pft",
                    models.BooleanField(
                        default=False, help_text="Pulmonary Function Test"
                    ),
                ),
                ("tmt", models.BooleanField(default=False, help_text="Treadmill Test")),
                ("echo_2d", models.BooleanField(default=False)),
                ("fluoroscopy", models.BooleanField(default=False)),
                ("x_ray_count", models.IntegerField(default=0)),
                ("ct_scan_count", models.IntegerField(default=0)),
                ("mri_count", models.IntegerField(default=0)),
                (
                    "x_ray_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "ct_scan_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "mri_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic_center",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_capabilities",
                        to="diagnostic_center.diagnosticcenter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dc_laboratory_capabilities",
            },
        ),
        migrations.CreateModel(
            name="DCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("registration_certificate", "Registration Certificate"),
                            (
                                "bio_medical_waste_certificate",
                                "Bio Medical Waste Management Certificate",
                            ),
                            ("building_permit", "Building Permit"),
                            ("fire_safety_license", "Fire Safety License"),
                            ("pndt_license", "PNDT License"),
                            (
                                "radiation_protection_certificate",
                                "Radiation Protection Certificate",
                            ),
                            ("pollution_noc", "Pollution Control NOC"),
                            ("nabh_nabl_certificate", "NABH/NABL/ISO Certificate"),
                            ("cancelled_cheque", "Cancelled Cheque"),
                            ("pan_card", "PAN Card"),
                            ("neft_declaration", "NEFT Declaration Form"),
                            ("gst_certificate", "GST Certificate"),
                            ("opd_tariff", "OPD Tariff"),
                            ("tpa_list", "List of TPAs"),
                            ("consultant_list", "List of Consultants"),
                            ("opd_schedule", "OPD Schedule"),
                            ("mou_copy", "MOU Copy"),
                            ("lol_legal", "LOL Legal Document"),
                            ("agreement", "Agreement Document"),
                            ("vendor_registration", "Vendor Registration Form"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="dc_documents/")),
                ("file_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="diagnostic_center.diagnosticcenter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_dc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dc_documents",
                "ordering": ["document_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DCContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("insurance_desk", "Insurance Desk"),
                            ("business_development", "Business Development"),
                            ("finance", "Finance"),
                            ("clinical_services", "Clinical Services"),
                            ("nursing_services", "Nursing Services"),
                            ("fund_transfer", "Fund Transfer"),
                            ("cashless_opd", "Cashless OPD"),
                            ("organization", "Organization Head"),
                            ("business_spoc", "Business SPOC"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="diagnostic_center.diagnosticcenter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dc_contacts",
                "ordering": ["department", "name"],
            },
        ),
    ]
